# ML Coding based Interview Problems

## Basic Pandas Execution (Very common for ML Freshers)

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({"Name": ["Alice", "Bob", "Charlie", "David", "Eva"], "Age": [25, np.nan, 30, np.nan, 45]})

### Filling missing values - Given a DataFrame with missing values in a numeric column, fill the NaNs with the median of that column.

In [ ]:
def fill_miss_value(df):
  median_age = df['Age'].median() # calculate median
  df['Age'] = df['Age'].fillna(median_age) # fill NaN cells with the median values
  return df

filled = fill_miss_value(df)
print(filled)

      Name   Age
0    Alice  25.0
1      Bob  30.0
2  Charlie  30.0
3    David  30.0
4      Eva  45.0

### You have a dataframe. How do you handle missing values in the 'Age' column by replacing them with the mean

In [ ]:
def clean_dataset(df):
    mean_age = df['Age'].mean() # define the mean of the Age
    df['Age'] = df['Age'].fillna(mean_age) # filled empty cells with the mean value in the 'Age' column
    return df

cleaned = clean_dataset(df)
print(cleaned)

      Name   Age
0    Alice  25.0
1      Bob  30.0
2  Charlie  30.0
3    David  30.0
4      Eva  45.0

### Given a DataFrame of employees with columns Name, Department, and Salary, return the names of people in 'Engineering' earning more than 50,000, sorted by Salary descending.

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Department': ['Engineering', 'Sales', 'Engineering', 'Engineering', 'Marketing'],
    'Salary': [75000, 48000, 62000, 91000, 52000]
}

df = pd.DataFrame(data)

result = df[(df['Department'] == 'Engineering') & (df['Salary'] > 5000)].sort_values(by='Salary', ascending=False)
print(result)

      Name   Department  Salary
3    Diana  Engineering   91000
0    Alice  Engineering   75000
2  Charlie  Engineering   62000

### Group By Aggregation - Given a DataFrame with columns Category and Price, return the average price for each category

In [ ]:
data = {
    'Category' : ['A', 'B', 'A', 'D', 'B'],
    'Price' : [4500, 5600, 1300, 3500, 2500]
}

df = pd.DataFrame(data)

result = df.groupby('Category')['Price'].mean().reset_index()
result.head()

  Category   Price
0        A  2900.0
1        B  4050.0
2        D  3500.0

### Apply Function: Given a DataFrame with a Text column, create a new column Word_Count by applying a custom function that counts the words in Text

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    'Text': [
        'Hello world',
        'This is a sample sentence',
        'Another example with multiple words',
        'Short one'
    ]
}

df = pd.DataFrame(data)

df['Word_Count'] = df['Text'].str.split().str.len()
df

# first the text was split into whitespaces using - split() string in-built function
# then the count of word / length was calculated using - len() string in-built function

                                  Text  Word_Count
0                          Hello world           2
1            This is a sample sentence           5
2  Another example with multiple words           5
3                            Short one           2

### One-Hot Encoding: Write a short script to convert a categorical column in a DataFrame into one-hot encoded columns using Pandas.

#### ⚠️**Hint** `get_dummies` function
- a pandas function that converts categorical variables into one-hot encoded binary columns

In [2]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'blue', 'red']
})

one_hot = pd.get_dummies(df['color'], prefix='color')
print(one_hot)

   color_blue  color_green  color_red
0       False        False       True
1        True        False      False
2       False         True      False
3        True        False      False
4       False        False       True